apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-cert
  namespace: default
spec:
  secretName: frontend-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: # put your domain name here
  dnsNames:
  - # put your domain name here
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-cert
  namespace: default
spec:
  secretName: backend-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: # put your domain name here
  dnsNames:
  - # put your domain name here
---